// People
export const PEOPLE_REQUEST = 'PEOPLE_REQUEST';
export const PEOPLE_SUCCESS = 'PEOPLE_SUCCESS';
export const PEOPLE_FAILURE = 'PEOPLE_FAILURE';
export const PEOPLE_MATCH_PLANET = 'PEOPLE_MATCH_PLANET';

// Planets
export const PLANETS_REQUEST = 'PLANETS_REQUEST';
export const PLANETS_SUCCESS = 'PLANETS_SUCCESS';
export const PLANETS_FAILURE = 'PLANETS_FAILURE';
